<?php

namespace AppBundle\Repository;

/**
 * passionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class passionsRepository extends \Doctrine\ORM\EntityRepository
{
}
