<?php

namespace AppBundle\Repository;

/**
 * presentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class presentationRepository extends \Doctrine\ORM\EntityRepository
{
}
